# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto Run Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start EasyConnect docker
        shell: bash
        run: |
          touch ~/.easyconn
          echo -e "https://vpn.hitsz.edu.cn\n${{ secrets.username }}\n${{ secrets.password }}" > setting.conf
          docker run --device /dev/net/tun --name 'EasyConnect' --cap-add NET_ADMIN -i -v $HOME/.easyconn:/root/.easyconn -p 127.0.0.1:1080:1080 -e EC_VER=7.6.7 hagb/docker-easyconnect:cli < setting.conf &

      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pysocks
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check VPN status
        shell: bash
        run: |
          sleep 30
          docker container ls
          docker container logs EasyConnect

      - name: Run daily report script
        shell: bash
        env:
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}
          GRADUATING: ${{ secrets.graduating }}
          API_KEY: ${{ secrets.api_key }}
        run: |
          python report.py "$USERNAME" "$PASSWORD" $GRADUATING -k "$API_KEY"
